id: A2B4FB728
title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth Deity
  White Jambhala'
type: translation
pechas:
- I3C3ABC76
- I4FAFA9BF
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:21.746916
  last_modified_at: 2023-01-04 11:27:21.746921
  collections:
  - Adeu Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I3C3ABC76/BDFC: 07F0
  I4FAFA9BF/904B: 07F0
